"""Current executor capability status."""

CAPABILITY_MATRIX = {
    "legacy_vba": {
        "status": "implemented",
        "notes": "Retained compatibility path using fixed AI_Enterprise_Runner.bas.",
    },
    "api_executor": {
        "status": "implemented",
        "notes": "Validates FeaturePlan v2 and supports PRD P0 plus conservative implemented P1 operations. Real calls require explicit confirmation.",
    },
    "create_new_part": {"status": "implemented"},
    "create_sketch": {"status": "implemented"},
    "sketch_center_rectangle": {"status": "implemented"},
    "sketch_circle": {"status": "implemented"},
    "extrude_boss": {"status": "implemented"},
    "extrude_cut": {"status": "implemented"},
    "create_through_hole": {"status": "implemented"},
    "create_blind_hole": {"status": "implemented"},
    "create_base_plate": {"status": "implemented"},
    "cut_corner_holes": {"status": "implemented"},
    "create_center_boss": {"status": "implemented"},
    "cut_center_hole": {"status": "implemented"},
    "add_fillet": {"status": "implemented"},
    "save_sldprt": {"status": "implemented"},
    "export_step": {"status": "implemented"},
    "capture_png": {"status": "implemented"},
    "rebuild_model": {"status": "implemented"},
    "validate_rebuild": {"status": "implemented"},
    "add_chamfer": {"status": "implemented"},
    "cut_slot": {"status": "implemented"},
    "create_counterbore_hole": {"status": "implemented"},
    "create_countersink_hole": {"status": "implemented"},
    "cut_rectangle_pocket": {"status": "implemented"},
    "create_linear_pattern": {"status": "implemented"},
    "create_circular_pattern": {"status": "implemented"},
    "create_revolve_boss": {"status": "scaffolded"},
    "create_revolve_cut": {"status": "scaffolded"},
    "create_sweep_boss": {"status": "scaffolded"},
    "create_sweep_cut": {"status": "scaffolded"},
    "create_loft_boss": {"status": "scaffolded"},
    "create_loft_cut": {"status": "scaffolded"},
    "add_shell": {"status": "scaffolded"},
    "add_rib": {"status": "scaffolded"},
    "add_draft": {"status": "scaffolded"},
    "mirror_feature": {"status": "implemented"},
    "set_material": {"status": "implemented"},
    "set_custom_property": {"status": "implemented"},
    "modify_named_dimension": {"status": "implemented"},
    "create_offset_plane": {"status": "implemented"},
    "create_axis": {"status": "implemented"},
    "create_reference_plane": {"status": "scaffolded"},
    "create_reference_axis": {"status": "scaffolded"},
}
